### ISSUE TITLE
Updating Working Directory Goes On Forever

### ISSUE THREAD

**Issue by ltwalt** [gitatomic/atomic_public#1]
When I execute a pull, I get the Working Directory and it continues for a long time

[2018-11-19_23-02-29.pdf](https://github.com/gitatomic/atomic_public/files/2598031/2018-11-19_23-02-29.pdf)

**Comment by gitatomic** [comment]
@ltwalt Hi, this is Artur, thank you for reporting that issue. 
Could you please answer to couple of questions?
1. Does it happen all the time?
2. Does it happen on every repository or just specific one?

Thank you and looking forward to hear from you
Best regards
Artur

**Comment by ltwalt** [comment]
It happens consistently on two different repos. Always have a pull that
updates files.

**Comment by ltwalt** [comment]
I have left it running for 30 minutes or more. The only way to stop it is to close the program. After you reopen the program everything seems fine.

**Comment by gitatomic** [comment]
Hi there,
Thank you for your reply. Yes, I've managed to reproduce that issue in our test environment. Issue has been assigned for fixing. You can expect fix to arrive no later than next Monday (26/11/2018). I will inform you about the update when it is ready for download.
Once again, thank you for reporting this issue.
Best regards 
Artur

**Comment by gitatomic** [comment]
Hi Walt, in the meantime, please download from the following link, GitAtomic 1.0.3 which is free of that issue. 

https://www.dropbox.com/s/4mals2thi7nqqmp/GitAtomic_Setup.exe?dl=1

I hope you'll enjoy using GitAtomic. If you have any comments/feedback or you experience any further difficulties, please let me know and I'll be happy to help.
Best regards
Artur

**Comment by gitatomic** [comment]
Hi Walt (and everyone)
New version of GitAtomic is available that has this issue fixed.

Once again Walt, thank you for reporting it.
Best regards
Artur
